language: node_js

before_install:
  - curl -sfL https://github.com/apex/apex/releases/download/v0.16.0/apex_linux_amd64 -o ./bin/apex --create-dirs
  - chmod +x ./bin/apex

install:
  - ./bin/apex version
  - yarn install --cwd ./functions/db-migrations

cache: yarn

deploy:
  provider: script
  script: ./bin/apex deploy
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    AWS_REGION: us-west-2